version: "3.9"

volumes:
  postgres_data:
  redis_data:

services:
  db:
    container_name: timetable_postgres
    image: postgres:13.0-alpine
    env_file:
      - .env
    ports:
      - 5445:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: timetable_redis
    image: redis:6.0.5
    entrypoint: redis-server --appendonly yes
    ports:
      - 6390:6379
    restart: always
    volumes:
      - redis_data:/data
